FROM openjdk:17-alpine
MAINTAINER baeldung.com
COPY target/code-challenge-0.0.1-SNAPSHOT.jar code-challenge-0.0.1-SNAPSHOT.jar
EXPOSE 9090
ENTRYPOINT ["java","-jar","/code-challenge-0.0.1-SNAPSHOT.jar"]